version: "1.0"
services:
  frontend:
    build: 
      context: ./frontend
      target: build
      platform: linux/amd64
    image: camscofie/travelrs:frontend
    ports: 
    - '3000:3000'
  backend:
    build: 
      context: ./backend
      target: build
      platform: linux/amd64
    image: camscofie/travelrs:backend
    ports: 
    - '8000:8000'
    
